# Generated by Django 6.1.1 on 2026-09-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='République Togolaise', max_length=100, verbose_name='Pays')),
                ('devise_nationale', models.CharField(blank=True, default='Travail - Liberté - Patrie', max_length=200, verbose_name='Devise nationale')),
                ('ministere', models.CharField(blank=True, help_text="Ex: Ministère des Enseignements Primaire, Secondaire, Technique et de l'Artisanat", max_length=255, verbose_name='Ministère de tutelle')),
                ('direction_regionale', models.CharField(blank=True, help_text="Ex: Direction Régionale de l'Éducation - Maritime", max_length=255, verbose_name='Direction régionale')),
                ('inspection', models.CharField(blank=True, help_text='Ex: IEPP Lomé Golfe', max_length=255, verbose_name='Inspection / IEPP')),
                ('prefecture', models.CharField(blank=True, help_text='Ex: Préfecture du Golfe', max_length=100, verbose_name='Préfecture')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune (optionnel)')),
                ('nom_officiel', models.CharField(blank=True, help_text="Nom tel qu'il doit apparaître sur les documents officiels", max_length=255, verbose_name='Nom officiel complet')),
                ('devise_ecole', models.CharField(blank=True, help_text='Ex: Travail - Discipline - Excellence', max_length=200, verbose_name="Devise / Slogan de l'école")),
                ('mode_en_tete', models.CharField(choices=[('textuel', 'Textuel (nom + logo)'), ('image', 'Image pré-imprimée (scan)')], default='textuel', max_length=20, verbose_name="Mode d'en-tête des documents")),
                ('en_tete_image', models.ImageField(blank=True, help_text="Utilisée uniquement si le mode est 'Image pré-imprimée'", null=True, upload_to='config/en_tetes/', verbose_name="Image d'en-tête pré-imprimée")),
                ('nom_chef', models.CharField(blank=True, max_length=150, verbose_name="Nom complet du chef d'établissement")),
                ('titre_chef', models.CharField(blank=True, help_text='Ex: Directeur, Proviseur, Principal', max_length=100, verbose_name='Titre du chef')),
                ('signature_chef', models.ImageField(blank=True, null=True, upload_to='config/signatures/', verbose_name='Signature scannée du chef')),
                ('cachet_ecole', models.ImageField(blank=True, null=True, upload_to='config/cachets/', verbose_name="Cachet / Sceau de l'école")),
                ('annee_fondation', models.CharField(blank=True, max_length=20, verbose_name='Année de fondation')),
                ('autorisation_ouverture', models.CharField(blank=True, max_length=100, verbose_name="N° d'autorisation d'ouverture")),
                ('sceau_ministere', models.ImageField(blank=True, null=True, upload_to='config/sceaux/', verbose_name='Sceau du ministère (optionnel)')),
                ('pied_de_page', models.TextField(blank=True, help_text='Texte affiché en bas des documents officiels', verbose_name='Pied de page personnalisé')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='core.etablissement')),
            ],
            options={
                'verbose_name': "Configuration d'établissement",
                'verbose_name_plural': "Configurations d'établissement",
            },
        ),
    ]
