# Generated by Django 6.1.1 on 2026-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configurationetablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='ville_document',
            field=models.CharField(blank=True, help_text="Ville utilisée pour 'Fait à ...' sur les documents", max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='annee_fondation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='autorisation_ouverture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='cachet_ecole',
            field=models.ImageField(blank=True, null=True, upload_to='config/cachets/'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='devise_ecole',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='devise_nationale',
            field=models.CharField(blank=True, default='Travail - Liberté - Patrie', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='direction_regionale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='en_tete_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/en_tetes/'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='inspection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='ministere',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='mode_en_tete',
            field=models.CharField(choices=[('textuel', 'Textuel (nom + logo)'), ('image', 'Image pré-imprimée (scan)')], default='textuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='nom_chef',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='nom_officiel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='pays',
            field=models.CharField(default='République Togolaise', max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='pied_de_page',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='sceau_ministere',
            field=models.ImageField(blank=True, null=True, upload_to='config/sceaux/'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='signature_chef',
            field=models.ImageField(blank=True, null=True, upload_to='config/signatures/'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='titre_chef',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin_principal', 'Admin Principal'), ('chef_etablissement', "Chef d'établissement"), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('enseignant', 'Enseignant'), ('surveillant', 'Surveillant')], max_length=30),
        ),
    ]
