# Generated by Django 6.1.1 on 2026-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configurationetablissement_ville_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='date_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='raison_suspension',
            field=models.TextField(blank=True, help_text='Motif affiché aux utilisateurs bloqués.'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='ville_document',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True, help_text='Un établissement inactif voit ses utilisateurs bloqués.'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
