# Generated by Django 6.1.1 on 2026-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etablissement_date_suspension_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['eleve__nom', 'matiere__ordre', 'matiere__nom'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='matiere',
            name='ordre',
            field=models.PositiveIntegerField(default=100, help_text="Ordre d'affichage (1 = en haut). Utile pour reproduire l'ordre du bulletin officiel."),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='libelle',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='raison_suspension',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(help_text='Ex: MATH, FR, ANG', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Coefficient par défaut de la matière (1 à 10)'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('etablissement', 'annee_scolaire', 'code')},
        ),
    ]
