# Generated by Django 6.1.1 on 2026-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_matiere_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom_parent',
            new_name='nom_mere',
        ),
        migrations.RenameField(
            model_name='eleve',
            old_name='telephone_parent',
            new_name='telephone_mere',
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nationalite',
            field=models.CharField(blank=True, default='Togolaise', max_length=50),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_tuteur',
            field=models.CharField(blank=True, help_text='Si différent des parents', max_length=200),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profession_tuteur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_tuteur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('complexe', 'Complexe scolaire')], default='complexe', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ordre',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
