# Generated by Django 6.1.1 on 2026-09-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nom_parent_eleve_nom_mere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='email_parent',
        ),
        migrations.AddField(
            model_name='eleve',
            name='adresse_mere',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='adresse_pere',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='adresse_tuteur',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse du tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_mere',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_pere',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_tuteur',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('redoublant', 'Redoublant'), ('transfere', 'Transféré')], default='nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse de l'élève"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du père'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_tuteur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du tuteur'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/', verbose_name='Photo (passeport)'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='profession_tuteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession du tuteur'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_mere',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de la mère'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du père'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_tuteur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du tuteur'),
        ),
    ]
