# Generated by Django 6.1.1 on 2026-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_eleve_email_parent_eleve_adresse_mere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_devoir',
        ),
        migrations.AddField(
            model_name='note',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_devoir1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Note du 1er devoir /20', max_digits=4),
        ),
        migrations.AddField(
            model_name='note',
            name='note_devoir2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Note du 2ème devoir /20', max_digits=4),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_composition',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Note de composition /20', max_digits=4),
        ),
    ]
