# Generated by Django 6.1.1 on 2026-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_note_note_devoir_note_date_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_composition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note de composition /20 (vide si non saisie)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_devoir1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note du 1er devoir /20 (vide si non saisie)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_devoir2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note du 2ème devoir /20 (vide si non saisie)', max_digits=4, null=True),
        ),
    ]
