# Generated by Django 6.1.1 on 2026-09-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_note_note_composition_alter_note_note_devoir1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='titulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_titulaire', to='core.enseignant', verbose_name='Professeur titulaire'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='note_passage',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Note minimale pour passer en classe supérieure (par défaut : 10/20)', max_digits=4, verbose_name='Note de passage'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_composition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_devoir1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_devoir2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
