# Generated by Django 6.1.1 on 2026-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_classe_titulaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='bp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Boîte Postale'),
        ),
    ]
