# Generated by Django 6.1.1 on 2026-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_etablissement_bp'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='prefecture_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Préfecture de naissance'),
        ),
    ]
