# Generated by Django 6.1.1 on 2026-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eleve_prefecture_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='prefecture_naissance',
            field=models.CharField(blank=True, choices=[('Maritime|Avé', 'Avé'), ('Maritime|Bas-Mono', 'Bas-Mono'), ('Maritime|Golfe', 'Golfe'), ('Maritime|Lacs', 'Lacs'), ('Maritime|Vo', 'Vo'), ('Maritime|Yoto', 'Yoto'), ('Maritime|Zio', 'Zio'), ('Maritime|Agoè-Nyivé', 'Agoè-Nyivé'), ('Plateaux|Agou', 'Agou'), ('Plateaux|Akébou', 'Akébou'), ('Plateaux|Amou', 'Amou'), ('Plateaux|Anié', 'Anié'), ('Plateaux|Danyi', 'Danyi'), ('Plateaux|Est-Mono', 'Est-Mono'), ('Plateaux|Haho', 'Haho'), ('Plateaux|Kloto', 'Kloto'), ('Plateaux|Kpélé', 'Kpélé'), ('Plateaux|Moyen-Mono', 'Moyen-Mono'), ('Plateaux|Ogou', 'Ogou'), ('Plateaux|Wawa', 'Wawa'), ('Centrale|Blitta', 'Blitta'), ('Centrale|Mô', 'Mô'), ('Centrale|Sotouboua', 'Sotouboua'), ('Centrale|Tchamba', 'Tchamba'), ('Centrale|Tchaoudjo', 'Tchaoudjo'), ('Kara|Assoli', 'Assoli'), ('Kara|Bassar', 'Bassar'), ('Kara|Binah', 'Binah'), ('Kara|Dankpen', 'Dankpen'), ('Kara|Doufelgou', 'Doufelgou'), ('Kara|Kéran', 'Kéran'), ('Kara|Kozah', 'Kozah'), ('Savanes|Cinkassé', 'Cinkassé'), ('Savanes|Kpendjal', 'Kpendjal'), ('Savanes|Kpendjal-Ouest', 'Kpendjal-Ouest'), ('Savanes|Oti', 'Oti'), ('Savanes|Oti-Sud', 'Oti-Sud'), ('Savanes|Tandjouaré', 'Tandjouaré'), ('Savanes|Tône', 'Tône')], max_length=100, verbose_name='Préfecture de naissance'),
        ),
    ]
