# Generated by Django 6.1.1 on 2026-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_eleve_prefecture_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='eleve',
            unique_together={('etablissement', 'matricule')},
        ),
    ]
