# Generated by Django 6.1.1 on 2026-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_eleve_matricule_alter_eleve_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='commune_administration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune administrative'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='perimetre_pedagogique',
            field=models.CharField(blank=True, max_length=255, verbose_name='Périmètre pédagogique'),
        ),
    ]
