# Generated by Django 6.1.1 on 2026-09-28 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configurationetablissement_commune_administration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateField()),
                ('heure_incident', models.TimeField(blank=True, null=True)),
                ('type_incident', models.CharField(choices=[('insolence', 'Insolence / manque de respect'), ('violence_physique', 'Violence physique'), ('violence_verbale', 'Violence verbale'), ('absence_non_justifiee', 'Absence non justifiée'), ('retard_repete', 'Retard répété'), ('tricherie', 'Tricherie'), ('vol_degradation', 'Vol / dégradation'), ('tenue_non_conforme', 'Tenue non conforme'), ('refus_obeissance', "Refus d'obéissance"), ('perturbation_cours', 'Perturbation du cours'), ('autre', 'Autre')], max_length=30)),
                ('gravite', models.CharField(choices=[('leger', 'Léger'), ('moyen', 'Moyen'), ('grave', 'Grave')], default='leger', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('traite', 'Traité'), ('classe', 'Classé')], default='signale', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_disciplinaires', to='core.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_disciplinaires', to='core.etablissement')),
                ('signale_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident disciplinaire',
                'verbose_name_plural': 'Incidents disciplinaires',
                'ordering': ['-date_incident', '-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('avertissement_oral', 'Avertissement oral'), ('avertissement_ecrit', 'Avertissement écrit'), ('travail_supplementaire', 'Travail supplémentaire'), ('renvoi_cours', 'Renvoi du cours'), ('exclusion_cours', 'Exclusion de cours (1-3 jours)'), ('exclusion_temporaire', 'Exclusion temporaire (4-8 jours)'), ('exclusion_definitive', 'Exclusion définitive'), ('convocation_parents', 'Convocation des parents'), ('exclusion', 'Exclusion'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_decidees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.etablissement')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.incidentdisciplinaire')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-date_debut', '-date_decision'],
            },
        ),
    ]
